/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class PainelPesquisa extends javax.swing.JPanel {

    String url = "jdbc:h2:tcp://localhost//BancoDeDados/TrabalhoBD";
    String usuario = "admin";
    String senha = "admin";
    
    FramePrincipal frame;
    
    public PainelPesquisa(FramePrincipal frame) {
        this.frame = frame;
        this.setVisible(false);
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        nomeTF = new javax.swing.JTextField();
        teleTF = new javax.swing.JTextField();
        celTF = new javax.swing.JTextField();
        enderecoTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        teleLabel = new javax.swing.JLabel();
        celLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        botaoEditar = new javax.swing.JButton();
        botaoPesquisar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(727, 423));

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setText("Pesquisar Pessoa");

        emailLabel.setText("E-mail:");

        nomeLabel.setText("Nome:");

        teleLabel.setText("Telefone:");

        celLabel.setText("Celular:");

        enderecoLabel.setText("Endereço:");

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });

        botaoPesquisar.setText("Pesquisar");
        botaoPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisarActionPerformed(evt);
            }
        });

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(214, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nomeLabel)
                            .addComponent(teleLabel)
                            .addComponent(celLabel)
                            .addComponent(enderecoLabel)
                            .addComponent(emailLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailTF)
                            .addComponent(enderecoTF)
                            .addComponent(celTF)
                            .addComponent(nomeTF)
                            .addComponent(teleTF, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botaoVoltar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(botaoPesquisar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoEditar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(botaoExcluir))
                            .addComponent(titulo))
                        .addGap(205, 205, 205))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teleLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoEditar)
                    .addComponent(botaoPesquisar)
                    .addComponent(botaoExcluir)
                    .addComponent(botaoVoltar))
                .addContainerGap(50, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditarActionPerformed
        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            System.out.println("Conectado.");
            String sql = "UPDATE PESSOA SET (TELEFONE, CELULAR, ENDERECO, EMAIL) = (?, ?, ?, ?) WHERE NOME = '"+nomeTF.getText()+"'";
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setString(1, teleTF.getText());
            ps.setString(2, celTF.getText());
            ps.setString(3, enderecoTF.getText());
            ps.setString(4, emailTF.getText());            
            ps.executeUpdate();
            ps.close();
            conexao.close();  
            JOptionPane.showMessageDialog(null, "Pessoa editada!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Deu erro na conexão. :(");
        }
    }//GEN-LAST:event_botaoEditarActionPerformed

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.setVisible(false);
        frame.painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisarActionPerformed
        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            System.out.println("Conectado.");
            String sql = "SELECT * FROM PESSOA WHERE NOME LIKE ('%"+nomeTF.getText()+"%')";
            PreparedStatement ps=conexao.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            rs.next();
            nomeTF.setText(rs.getString("NOME"));
            teleTF.setText(rs.getString("TELEFONE"));
            celTF.setText(rs.getString("CELULAR"));
            enderecoTF.setText(rs.getString("ENDERECO"));
            emailTF.setText(rs.getString("EMAIL"));
            rs.close();
            conexao.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Deu erro na conexão. :(");
        }
    }//GEN-LAST:event_botaoPesquisarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            System.out.println("Conectado.");
            String sql = "DELETE FROM PESSOA WHERE NOME = '"+nomeTF.getText()+"'";
            PreparedStatement ps=conexao.prepareStatement(sql);
            ps.executeUpdate();
            ps.close();
            conexao.close();
            nomeTF.setText("");
            teleTF.setText("");
            celTF.setText("");
            enderecoTF.setText("");
            emailTF.setText("");
            JOptionPane.showMessageDialog(null, "Pessoa excluida com sucesso.");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Deu erro na conexão. :(");
            Logger.getLogger(PainelPesquisa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JButton botaoPesquisar;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel celLabel;
    private javax.swing.JTextField celTF;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTF;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JTextField teleTF;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
