/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import JavaBeans.Pessoa;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class PainelCadastro extends javax.swing.JPanel {
    
    String url = "jdbc:h2:tcp://localhost//BancoDeDados/TrabalhoBD";
    String usuario = "admin";
    String senha = "admin";

    FramePrincipal frame;
    
    public PainelCadastro(FramePrincipal frame) {
        this.frame = frame;
        
        this.setVisible(false);
        initComponents();
        try {
            Class.forName("org.h2.Driver");
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "Driver não foi Encontrado.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        botaoCadastro = new javax.swing.JButton();
        botaoVoltar = new javax.swing.JButton();
        nomeTF = new javax.swing.JTextField();
        teleTF = new javax.swing.JTextField();
        celTF = new javax.swing.JTextField();
        enderecoTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        nomeLabel = new javax.swing.JLabel();
        teleLabel = new javax.swing.JLabel();
        celLabel = new javax.swing.JLabel();
        enderecoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(727, 423));
        setPreferredSize(new java.awt.Dimension(727, 423));

        titulo.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        titulo.setText("Cadastrar Pessoa");

        botaoCadastro.setText("Cadastrar");
        botaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCadastroActionPerformed(evt);
            }
        });

        botaoVoltar.setText("Voltar");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        nomeLabel.setText("Nome:");

        teleLabel.setText("Telefone:");

        celLabel.setText("Celular:");

        enderecoLabel.setText("Endereço:");

        emailLabel.setText("E-mail:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(212, Short.MAX_VALUE)
                .addComponent(titulo)
                .addGap(210, 210, 210))
            .addGroup(layout.createSequentialGroup()
                .addGap(233, 233, 233)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoVoltar)
                    .addComponent(nomeLabel)
                    .addComponent(teleLabel)
                    .addComponent(celLabel)
                    .addComponent(enderecoLabel)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emailTF)
                    .addComponent(enderecoTF)
                    .addComponent(celTF)
                    .addComponent(nomeTF)
                    .addComponent(teleTF)
                    .addComponent(botaoCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(titulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomeTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(teleTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teleLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(celTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(celLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(enderecoTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(enderecoLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoCadastro)
                    .addComponent(botaoVoltar))
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        this.setVisible(false);
        frame.painelPrincipal.setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void botaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCadastroActionPerformed
        Pessoa p = new Pessoa();
        p.setNome(nomeTF.getText());
        p.setTelefone(teleTF.getText());
        p.setCelular(celTF.getText());
        p.setEndereco(enderecoTF.getText());
        p.setEmail(emailTF.getText());
        
        try {
            Connection conexao = DriverManager.getConnection(url, usuario, senha);
            System.out.println("Conectado.");
            String sql = "INSERT INTO PESSOA (NOME, TELEFONE, CELULAR, ENDERECO, EMAIL) VALUES (?, ?, ?, ?, ?)";
            PreparedStatement ps = conexao.prepareStatement(sql);
            ps.setString(1, p.getNome());
            ps.setString(2, p.getTelefone());
            ps.setString(3, p.getCelular());
            ps.setString(4, p.getEndereco());
            ps.setString(5, p.getEmail());
            ps.executeUpdate();
            ps.close();
            conexao.close();      
            JOptionPane.showMessageDialog(null, "Pessoa cadastrada!");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Deu erro na conexão. :(");
        }
        
    }//GEN-LAST:event_botaoCadastroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCadastro;
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JLabel celLabel;
    private javax.swing.JTextField celTF;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JTextField emailTF;
    private javax.swing.JLabel enderecoLabel;
    private javax.swing.JTextField enderecoTF;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTF;
    private javax.swing.JLabel teleLabel;
    private javax.swing.JTextField teleTF;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
